### ISSUE TITLE
broken app

### ISSUE THREAD

**Issue by JSparrow93** [luisflorido/wallhaven-desktop#5]
When trying to run in mac os 14.4 beta it refuses to open and mac os asks to put it in the trash.

**Comment by luisflorido** [comment]
@JSparrow93 Can you test on [1.0.3](https://github.com/luisflorido/wallhaven-desktop/releases/tag/v1.0.3)?

**Comment by JSparrow93** [comment]
just tested it. Same issue.

**Comment by luisflorido** [comment]
Seems to be a bug related to https://github.com/electron/electron/issues/34253, can you try on [1.0.4](https://github.com/luisflorido/wallhaven-desktop/releases/tag/v1.0.4)? I don't have access to 14.4 beta for now, but I'll update if the problem persists

**Comment by JSparrow93** [comment]
The problem still persists 

![IMG_1395](https://github.com/luisflorido/wallhaven-desktop/assets/24133811/f2a365b1-dfb0-4269-b62f-8cae01e3efc1)

**Comment by JSparrow93** [comment]
I did also disable beta updates so once 14.4 stable comes out I will stay on stable. Atleast till wwdc.

**Comment by luisflorido** [comment]
Seems to be a signing problem, if you run:
`xattr -d com.apple.quarantine <app path>`
This will remove the attribute that says the executable is damaged (this is because I don't have a paid subscription to upload)
Issue thread: https://discussions.apple.com/thread/253714860?answerId=257037956022&sortBy=best#257037956022

**Comment by JSparrow93** [comment]
Thank you. It did now open, no problem. and that is definitely a command I will save.
